# Generated by Django 3.2.9 on 2021-11-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Movie')),
                ('description', models.TextField(verbose_name='Description')),
                ('likes', models.IntegerField(default=0, null=True)),
                ('rate', models.PositiveBigIntegerField(default=0, null=True)),
                ('production_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
