# Generated by Django 3.2.9 on 2021-11-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(null=True, upload_to='', verbose_name='movie/movie/images'),
        ),
    ]
